spring.application.name=pacientes


spring.datasource.url=jdbc:postgresql://localhost:5432/pacientes
spring.datasource.username=postgres
spring.datasource.password=William3342*
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.operationsSorter=method
