spring.application.name=pacientes

# URL de conexión a tu base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/pacientes
spring.datasource.username=postgres
spring.datasource.password=William3342*
spring.datasource.driver-class-name=org.postgresql.Driver

# Muestra en consola las consultas SQL que se ejecuten
spring.jpa.show-sql=true

# Crea/actualiza las tablas automáticamente según las entidades (solo para desarrollo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.operationsSorter=method
